const heroes = [
  new Character({
    name: "Ash Thunderbelt",
    party: "Good",
    health: 25,
    maxHealth: 25,
    attackPower: 4,
    defense: 1,
    attackCall: "Huuagh",
    deathCall: "Bleaahhhh",
    speed: 15,
    initiative: 2,
    isDead: false,
    controlledBy: "player",
    race: {
      name: RaceName.Human,
    },
  }),
];

const enemies = [
  new Character({
    // TODO: Make a separate race property
    type: "greedy goblin",
    name: "Gragnok",
    party: "Bad",
    health: 10,
    maxHealth: 10,
    attackPower: 2,
    defense: 0,
    attackCall: "Graaah",
    deathCall: "Aaaak",
    speed: 10,
    initiative: 3,
    isDead: false,
    controlledBy: "ai",
    gold: 15,
    race: {
      name: RaceName.Goblin,
    },
  }),
  new Character({
    type: "giant rat",
    name: "Remmy",
    party: "Bad",
    health: 4,
    maxHealth: 4,
    attackPower: 1,
    defense: 0,
    attackCall: "Squeak",
    deathCall: "Reeee",
    speed: 20,
    initiative: 1,
    isDead: false,
    controlledBy: "ai",
    gold: 2,
    race: {
      name: RaceName.Rodent,
    },
  }),
  new Character({
    type: "lesser troll",
    name: "Jeff",
    party: "Bad",
    health: 20,
    maxHealth: 20,
    attackPower: 4,
    defense: 2,
    attackCall: "Hrag",
    deathCall: "Woaaahhhh",
    speed: 7,
    initiative: 4,
    isDead: false,
    controlledBy: "ai",
    gold: 25,
    race: {
      name: RaceName.Troll,
    },
  }),
];
